package model.analysis.textFormatters;

import java.util.List;

import model.ImageEntry;
import model.Location;
import model.Species;
import model.analysis.DataAnalysis;
import model.analysis.PredicateBuilder;

/**
 * The text formatter the "all pictures" file generated by DataAnalyze
 * 
 * @author David Slovikosky
 */
public class AllPicturesFormatter extends TextFormatter
{
	public AllPicturesFormatter(List<ImageEntry> images, DataAnalysis analysis)
	{
		super(images, analysis);
	}

	/**
	 * <p>
	 * All pictures is a file that contains a list of each species, location, and image file photographed
	 * 
	 * @return Returns a string representing the data in a clean form
	 */
	public String createAllPictures()
	{
		String toReturn = "";

		for (Location location : analysis.getAllImageLocations())
		{
			List<ImageEntry> withLocation = new PredicateBuilder().locationOnly(location).query(images);
			for (Species species : analysis.getAllImageSpecies())
			{
				List<ImageEntry> withLocationSpecies = new PredicateBuilder().speciesOnly(species).query(withLocation);
				for (ImageEntry imageEntry : withLocationSpecies)
				{
					toReturn = toReturn + String.format("%-28s %-28s %-28s\n", location.getName(), species.getName(), imageEntry.getImageFile().getName());
				}
			}
		}

		if (!toReturn.isEmpty())
			toReturn = toReturn.substring(0, toReturn.length() - 1);

		return toReturn;
	}
}
