language: java
dist: trusty
jdk:
  - openjdk15

cache:
  directories:
    - $HOME/.m2

script:
  - cd Sanimal\ FX
  - mvn -U compile package

before_deploy:
  - mv target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar target/sparcd.jar

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: target/sparcd.jar
  on:
    tags: true
