name: "pre-release"

on:
  push:
    branches: [ Sanimal-No-ES ]
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:

  gh_pre_release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-14]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build with Maven
        if: ${{ matrix.platform != 'macos-14' }}
        run: cd "Sanimal FX" && mvn -U compile package && mv target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar ../sparcd-${{ matrix.platform }}.jar

      - name: Build with Maven Mac Silicon
        if: ${{ matrix.platform == 'macos-14' }}
        run: cd "Sanimal FX" && mvn -U -Denv=MacSilicon compile package && mv target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar ../sparcd-MacSilicon.jar

      - name: Upload prerelease assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Prerelease Build
          files: sparcd-${{ matrix.platform }}.jar
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
