name: "pre-release"

on:
  push:
    branches: [ Sanimal-No-ES ]
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: prerelease
          name: Development Build
          draft: true
          prerelease: true

  gh_pre_release:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build with Maven
        run: cd "Sanimal FX" && mvn -U compile package && mv target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar ../sparcd-${{ matrix.platform }}.jar

      - name: Upload release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This is how it will be labeled on the release page.
          default_release_name: Prerelease Build
          # The path to the file you want to upload.
          file: sparcd-${{ matrix.platform }}.jar
          # This is a prerelease
          prerelease: true
          # Noisy output
          verbose: true
          # Overwrite existing items
          overwrite: true
