name: "pre-release"

on:
  push:
    branches: [ Sanimal-No-ES ]
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:

  gh_pre_release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        include:
          - platform: ubuntu-latest
            jar_file_name: sparcd-ubuntu-latest.jar
          - platform: windows-latest
            jar_file_name: sparcd-windows-latest.jar
          - platform: macos-latest
            jar_file_name: macos-latest.jar
          - platform: macos-14
            jar_file_name: sparcd-AppleSilicon.jar
            extra_maven_flags: -Denv=AppleSilicon

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build with Maven
        run: cd "Sanimal FX" && mvn -U ${{ extra_maven_flags }} compile package && mv target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar ../${{ matrix.jar_file_name }}

      - name: Upload prerelease assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Prerelease Build
          files: ${{ matrix.jar_file_name }}
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
